#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionComponentExplorer.Resource", IsApplication=true)]

namespace ActionComponentExplorer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ActionComponents.Resource.String.library_name = global::ActionComponentExplorer.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddToCloud = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Agreement = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Airplane = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ATMCard = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Boat = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Bookmark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Breifcase = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Bridge = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Brightness = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int CalendarDay = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CalendarDayofWeek = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CalendarMonth = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CalendarWeek = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Chat = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Chats = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Checkmark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Clipboard = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Clock = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ClosedMail = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Cloud = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Contrast = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Crop = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Cut = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int FilmRoll = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Folder = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Fountain = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Gear = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int GoLight = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int GroceryBag = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int House = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int iconBrightness = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Key = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int License = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int LightOff = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int LightOn = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Link = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Lock = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ManWithChild = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Marker = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Microphone = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Monitor = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Movie = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Music = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int OpenMail = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Paste = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Picture = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Polaroid = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Portfolio = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Radio = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int RadioTower = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int RemoveFromCloud = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Scanner = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ShoppingBag = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int StopLight = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Tag = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Tools = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int TV = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Unlocked = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Wallet = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Widescreen = 2130837564;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int tileController = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
